apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-tester
  template:
    metadata:
      labels:
        app: service-tester
    spec:
      containers:
      - name: service-tester
        image: rohit108kolhe/service-tester:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-tester
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: service-tester
